services:
  - type: web
    name: weather-predictor
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    branch: main
    autoDeploy: true
